steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
            '-t', 'gcr.io/public-lab/image-sequencer-app:$SHORT_SHA', 
            '-t', 'gcr.io/public-lab/image-sequencer-app:latest', 
            '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/public-lab/image-sequencer-app']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mapknitter-exporterjs-kubes', '*=gcr.io/public-lab/image-sequencer-app:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mapknitter'
images: ['gcr.io/public-lab/image-sequencer-app']
